# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


trigger:
- develop

variables:
  buildConfiguration: 'release'
  buildTag: '$(Build.BuildId)'
  tag: 'latest'

stages:
- stage: 'stageBuild'
  displayName: Copy Release build to artifact staging
  jobs:
   - job: 'jobBuild'
     pool:
         vmImage: ubuntu-latest
       
     steps:
     - task: Gradle@2
       inputs:
         workingDirectory: ''
         gradleWrapperFile: 'gradlew'
         gradleOptions: '-Xmx3072m'
         javaHomeOption: 'JDKVersion'
         jdkVersionOption: '1.8'
         jdkArchitectureOption: 'x64'
         publishJUnitResults: true
         testResultsFiles: '**/TEST-*.xml'
         tasks: 'build'
     - task: CopyFiles@2
       displayName: Copy Release build to artifact staging
       condition: succeeded()
       inputs:
         sourceFolder: './build/libs/'
         contents: 'present-verb-*.jar'
         targetFolder: '$(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
         CleanTargetFolder: true
     - publish: '$(Build.ArtifactStagingDirectory)'
       displayName: 'Publish script'
       artifact: em-learning-artifacts
     - task: UniversalPackages@0
       inputs:
         command: 'publish'
         publishDirectory: '$(Build.ArtifactStagingDirectory)'
         feedsToUsePublish: 'internal'
         vstsFeedPublish: 'b6ad1af1-03f8-4fb8-905c-0febec8041fa/9708f494-a4a3-4cad-918a-b34763bacfcb'
         vstsFeedPackagePublish: 'ejemplo'
         versionOption: 'patch'
     - task: ArchiveFiles@2
       inputs:
         rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
         includeRootFolder: true
         archiveType: 'zip'
         tarCompression: 'gz'
         archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
         replaceExistingArchive: true
     - task: Docker@2
       displayName: Build and push an image to container registry
       inputs:
         containerRegistry: 'b6458ad2-36f6-4d5a-82fb-e7467aafd728'
         repository: 'emlearningimage'
         command: 'buildAndPush'
         Dockerfile: '**/Dockerfile'
         buildContext: '$(System.DefaultWorkingDirectory)/'
         tags: |
           $(buildTag)
           $(tag)