#server:
#   port: 8091
#   servlet:
#      context-path: /api/present/verb

server:
  port: ${PORT:5000}
  servlet:
    context-path: /api/present/verb

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-236-137-173.compute-1.amazonaws.com:5432/d92ai8qk17f193?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: "oshuylewjbhjye"
    password: "f734413fb0145ed0532a791e611e262a2a27875ab1da09c5c8e5e369f4b6ccad"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: giftu
    
    
security:
  jwt:
    token:
      secret-key: jwtGiftUSecretKey
      expire-length: 86400    
   