server:
   port: 8091 
   servlet:
      context-path: /api/present/verb  

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.9:5432/present_db
    username: "english_user"
    password: "english123"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: giftu
    
    
security:
  jwt:
    token:
      secret-key: jwtGiftUSecretKey
      expire-length: 86400    
   