#server:
#   port: 8091
#   servlet:
#      context-path: /api/present/verb

server:
  port: ${PORT:8091}
  servlet:
    context-path: /api/present/verb

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dbpostgresql:5432/em_learning_db
    username: "postgres"
    password: "123456"
    #maximumPoolSize: 5
    hikari:
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      #ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: giftu


security:
  jwt:
    token:
      secret-key: jwtGiftUSecretKey
      expire-length: 86400    
   